name: GitHub CI Single Action MATLAB Pipeline
on: [push]
env:
  MATLAB_LOG_FILE: "MATLAB_Log_Output.txt"
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts and CI pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
#          release: R2023b
          products: Simulink Simulink_Test Simulink_Coverage
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2
        with:
          test-results-junit: test-results/results.xml
          test-results-pdf: test-results/results.pdf
          test-results-simulink-test: test-results/results.mldatx
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
      - name: run process action
        run: matlab -nodesktop -logfile "$MATLAB_LOG_FILE" -batch "openProject(pwd);runprocess(Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);"